### ISSUE TITLE
[Proposal] HexLayout

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#111]
# HexLayout

* [x] Proposed
* [x] Prototype
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

A Layout that arranges the elements in a honeycomb pattern

## Detailed Design
[design]: #detailed-design

### HexLayout.shared.cs

```cs
public class HexLayout : Layout<View>
{
  public static readonly BindableProperty OrientationProperty;
  public static readonly BindableProperty ColumnCountProperty;
  public static readonly BindableProperty RowCountProperty;
  public static readonly BindableProperty ColumnProperty;
  public static readonly BindableProperty RowProperty;
  
  public HexOrientation Orientation { get; set; }
  public int ColumnCount { get; set; }
  public int RowCount { get; set; }
  public int Column { get; set; }
  public int Row { get; set; }

  public static int GetColumn(BindableObject b);
  public static void SetColumn(BindableObject b);
}
```

## Usage Syntax
[usage]: #usage-syntax

<!-- Here is an example from CharactersValidationBehavior:

### XAML Usage

```xml
<xct:HexLayout Orientation="Vertical" RowCount="5" ColumnCount="5">
        <BoxView xct:HexLayout.Row="0" xct:HexLayout.Column="1" CornerRadius="24" BackgroundColor="#006699" Margin="12"/>
        <BoxView xct:HexLayout.Row="0" xct:HexLayout.Column="2" CornerRadius="24" BackgroundColor="#0033CC" Margin="12"/>
        <BoxView xct:HexLayout.Row="0" xct:HexLayout.Column="3" CornerRadius="24" BackgroundColor="#3333FF" Margin="12"/>
</xct:HexLayout>
```

**Comment by vhugogarcia** [comment]
Hello @brminnick,

After reviewing this issue and how the HexLayout is expected to work, I noticed that we can achieve the same layout very easily by using .NET MAUI geometry. See an Hexagon layout sample below, and a screenshot of a quick demo I did trying to replicate the Honeycomb Hexagon layout. 

```xml
<HorizontalStackLayout HorizontalOptions="Center">
			<Grid BackgroundColor="Orange" HeightRequest="31.25" WidthRequest="36" VerticalOptions="Center" HorizontalOptions="Center" Margin="0,0,0,0">
				<Grid.Clip>
				<PathGeometry Figures="m0.32332,15.45189l7.64286,-15.33333l20.38096,0l7.64286,15.33333l-7.64286,15.33333l-20.38096,0l-7.64286,-15.33333z"/>
				</Grid.Clip>
			</Grid>
			<Grid BackgroundColor="Pink" HeightRequest="31.25" WidthRequest="36" VerticalOptions="Center" HorizontalOptions="Center" Margin="31,0,0,0">
				<Grid.Clip>
				<PathGeometry Figures="m0.32332,15.45189l7.64286,-15.33333l20.38096,0l7.64286,15.33333l-7.64286,15.33333l-20.38096,0l-7.64286,-15.33333z"/>
				</Grid.Clip>
			</Grid>
			<Grid BackgroundColor="BlueViolet" HeightRequest="31.25" WidthRequest="36" VerticalOptions="Center" HorizontalOptions="Center" Margin="31,0,0,0">
				<Grid.Clip>
				<PathGeometry Figures="m0.32332,15.45189l7.64286,-15.33333l20.38096,0l7.64286,15.33333l-7.64286,15.33333l-20.38096,0l-7.64286,-15.33333z"/>
				</Grid.Clip>
			</Grid>
</HorizontalStackLayout>
```

I am not saying that this layout could help others to do it, however, since .NET MAUI already provides very solid path geometry features, we as developers can use the built-in features. Also, what if the user instead of an Hexagon figure wants another geometry like Octagon or trapezoid, this is going to become an endless feature to provide support.

**Note**: I may be wrong, but I wanted to share my grain of salt. 😄 

![Simulator Screenshot - iPhone 15 Plus - 2023-09-25 at 09 43 28](https://github.com/CommunityToolkit/Maui/assets/1047398/4f2af4ca-e7d0-46a0-bccc-17dd595485fc)

**Comment by brminnick** [comment]
Oh - nice!!

What's your recommendation for moving forward? Should we close this Proposal as it's basically already implemented in .NET MAUI, or should we still implement HexLayout using .NET MAUI's Path geometry?

**Comment by vhugogarcia** [comment]
Hey @brminnick, I recommend to close this proposal, and eventually in the future if people is actively looking for some extensions or solutions, we can always start a new discussion and provide more information.
