### ISSUE TITLE
[BUG] Cannot open another popup shortly after closing the previous one on iOS.

### ISSUE THREAD

**Issue by marekm294** [CommunityToolkit/Maui#1111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I try to open pupup on iOS right after closing the previous one, the popup is not opened.

### Expected Behavior

I expect to see the next popup after I close the previous one as it works on android.

### Steps To Reproduce

Open app and push button "Test!". Click all next buttons.

### Link to public reproduction project repository

https://github.com/marekm294/PopupCantBeOpenedBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS:iOS 16.3.1
- .NET MAUI:7.0.52
```

### Anything else?

You can use await Task.Delay() as workaround.

**Comment by acaliaro** [comment]
#1168

**Comment by kaushik-sarker** [comment]
The issue is not fixed. Even after using CloseAsync(), the popup is sometimes not closed. 
Reproduction steps: 
1. Open the pop-up
2. Immediately close the popup (you can wait a few milliseconds; I am calling an API in the meantime). 
Could you follow the steps several times? The popup will not be closed at some point. 
I have used Task.Delay(50). It improves a little bit but does not fully fix the issue.

**Comment by bijington** [comment]
Why would you try to close a popup so quickly? For something visual that would provide a poor user experience and I would argue it's not a valid use case

**Comment by kaushik-sarker** [comment]
I want to display a loading indicator in a pop-up while calling an API, as I want to prevent user interaction until that call is finished, and that API response time might be very fast. I believe this is a valid use case.

**Comment by svaldetero** [comment]
Just to support the validity of the use case, I show a blocking popup while making a network call for the same reason. And if the call fails, I might want to show an error popup informing the user. So that would be a popup that shows really quick, then closes, then has a different popup shown immediately after.

**Comment by bijington** [comment]
> I want to display a loading indicator in a pop-up while calling an API, as I want to prevent user interaction until that call is finished, and that API response time might be very fast. I believe this is a valid use case. 
> 
> Sorry, I forgot to mention that the behavior is in the Windows desktop application, and I am not sure about IOS or Android.

Having a popup flash before a user will provide a poor user experience and if it flashes very quickly you even run the risk of triggering a seizure in some people.

What I would propose you do in this scenario is always show your popup for at least a period of time (say 3s) therefore the popup won't flash before the user. Or add a button allowing the user to dismiss it themselves depending on your flow.

**Comment by bijington** [comment]
> Just to support the validity of the use case, I show a blocking popup while making a network call for the same reason. And if the call fails, I might want to show an error popup informing the user. So that would be a popup that shows really quick, then closes, then has a different popup shown immediately after.

I would argue that a better user experience here would be to show a single popup that includes the loading and also any error display as well. This would provide a single focal point for the user. Showing something, hiding it and then showing something else related doesn't feel quite right to me.

**Comment by bijington** [comment]
That being said in an ideal solution I would prefer us to queue up the calls rather than silently fail. I don't know the feasibility of this right now though. I'd have to check the implementations to find out why

**Comment by svaldetero** [comment]
> I would argue that a better user experience here would be to show a single popup that includes the loading and also any error display as well. This would provide a single focal point for the user. Showing something, hiding it and then showing something else related doesn't feel quite right to me.

While I understand your reasoning behind it and it makes sense, that doesn't mean it is always feasible. Those popups could have different designs, sizes, and functions and repurposing one to do all isn't always best.

> What I would propose you do in this scenario is always show your popup for at least a period of time (say 3s)

We can agree to disagree, because, my opinion, is that artificially blocking the UI for a minimum of 3s if not needed is a poor user experience. 

My point was not to say that my way, @kaushik-sarker 's way, or your way is right or wrong. It was to say that even though we disagree, the scenarios are still valid for our use cases.

**Comment by bijington** [comment]
I am happy to accept there are use cases different to my suggestions :). I was hoping the suggestions would help to find a nice workaround to the issue. If you wanted to manage a more complex UI inside a Popup I would advocate for using our StateContainer.

I agree that the toolkit should present a Popup if Show is called and as I mentioned in another comment I think we should queue up the calls so that when you call Show we do actually Show the Popup.

3s might be too long but I think everyone would agree that showing a Popup for something like 50ms is a never good idea.

Did you say that you are experiencing the issue on Windows?

**Comment by svaldetero** [comment]
> Did you say that you are experiencing the issue on Windows?

My apologies for adding to the noise. I only had the issue on iOS and am not developing on Windows. I am following this item to see about fixes / updates. I only chimed in to support the other person's use case.

**Comment by bijington** [comment]
There's no need to apologise - I certainly don't consider it noise. Oh wait... am I noisy too? 😂

**Comment by kaushik-sarker** [comment]
> I am happy to accept there are use cases different to my suggestions :). I was hoping the suggestions would help to find a nice workaround to the issue. If you wanted to manage a more complex UI inside a Popup I would advocate for using our StateContainer.
> 
> I agree that the toolkit should present a Popup if Show is called and as I mentioned in another comment I think we should queue up the calls so that when you call Show we do actually Show the Popup.
> 
> 3s might be too long but I think everyone would agree that showing a Popup for something like 50ms is a never good idea.
> 
> Did you say that you are experiencing the issue on Windows?

Thanks for your suggestion, Bijington. 
I also think we should not block user interaction for a fixed amount of time just to make sure the popup is displaying properly.

> Did you say that you are experiencing the issue on Windows?
Yes, I am experiencing this on windows.

What I am doing is calling the Show() method (fire and forget) to display the popup with a loading indicator and when the network call is resolved I am calling CloseAsync() (I tried Close(); but the same luck). 
I have a gut feeling that the popup is displaying on the screen after the CloseAsync() method has already taken place.

**Comment by bijington** [comment]
> I also think we should not block user interaction for a fixed amount of time just to make sure the popup is displaying properly.

The purpose of showing the popup for at least some time is not to make sure the popup has displayed properly, it's to make sure the user actually sees it and can read it. Rather than seeing something flash on screen and they have no clue what it meant. Anyway I can accept people don't like this idea.

> Yes, I am experiencing this on windows.
> 
> What I am doing is calling the Show() method (fire and forget) to display the popup with a loading indicator and when the network call is resolved I am calling CloseAsync() (I tried Close(); but the same luck). 
> 
> I have a gut feeling that the popup is displaying on the screen after the CloseAsync() method has already taken place. 

So if this is the case it is definitely not a valid use case in my opinion. You can't expect to close something that hasn't finished showing. At the least I would suggest trying the following:
- Show and await the popup
- Make API call and await
- Close the popup

**Comment by kaushik-sarker** [comment]
> Show and await the popup

This approach has a problem. This will await forever until we return the result by calling CloseAsync(result)

**Comment by bijington** [comment]
Doh! You are correct! Then I would kick off the API call once the Popup has opened, you can subscribe to the Opened event I think. Or if you have a view model behind use the IPopupService to manage that.

**Comment by bijington** [comment]
Or just call Show instead as you want it to be synchronous

**Comment by kaushik-sarker** [comment]
> Then I would kick off the API call once the Popup has opened

No, that is not working either. The popup is not closed after calling the CloseAsync method. If I set a break point there, then it works.
I think my intuition that the popup was being closed before it was shown was not correct.

**Comment by bijington** [comment]
OK, this sounds like it is not strictly related to this issue, plus this one is currently closed. Can you try opening a new issue with your code and I can try and take a look?

**Comment by kaushik-sarker** [comment]
I have narrowed it down - the issue is happening only inside the OnAppearing() overridden method. 
I have created an issue: https://github.com/CommunityToolkit/Maui/issues/1705
