### ISSUE TITLE
[BUG] EventToCommandBehaviour cannot be resolved when used in MAUI Library project.

### ISSUE THREAD

**Issue by Knots23** [CommunityToolkit/Maui#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using the _EventToCommandBehavior_ in a MAUI Library project, it fails to compile and results in:
XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:EventToCommandBehavior".

<img width="607" alt="image" src="https://user-images.githubusercontent.com/23098180/228345674-05d9b48a-5538-40c5-ba83-3d0090df17b4.png">

When used in the main project, it does compile.

### Expected Behavior

The behavior can be used in a MAUI Library project as well.

### Steps To Reproduce

1. Open the solution.
2. Compile it (tested both Windows and Android)
3. Note the error.

### Link to public reproduction project repository

https://github.com/Knots23/MAUI-toolkit-bug-EventToCommandBehavior-2023-03-28

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Windows / Android
- .NET MAUI: 7.0.49/7.0.100
- Installation Source: VS 17.4.33110.190
```

**Comment by brminnick** [comment]
The linker is removing the our library from your project. This happens when the compiler removes "unused" third-party libraries and it happens because the linker isn't intelligent enough to understand that the library is being used in XAML (it only knows how to scan C# code).

Add the following code to `MainPage.xaml` which will generate a C# property for your code-behind; during compilation, the linker will now see that you are using `CommunityToolkit.Maui` and will no longer remove it:

```xaml
<toolkit:EventToCommandBehavior x:Name="EventToCommandBehavior" EventName="Appearing" Command="{Binding AppearingCommand}" />
```

**Comment by Knots23** [comment]
@brminnick Thanks for the quick reply!
Adding the x:Name to the behavior does solve our issue. Maybe this could be added to the documentation page.
Thanks.

**Comment by brminnick** [comment]
You're welcome! This is a known bug in .NET / Mono.

But agreed - perhaps there's a better way for us to handle this.
