### ISSUE TITLE
Label does not wrap when embedded within a Grid in an Expander Content section.

### ISSUE THREAD

**Issue by srqdevg** [CommunityToolkit/Maui#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

A long text label does not wrap when embedded within a Grid that is inside an expander content section.

### Expected Behavior

Label would wrap and content section expand to show all contents.

### Steps To Reproduce

I was converting over a simple bullet list control from Xamarin to Maui and the behavior of labels is not as expected. If you open the solution from [https://github.com/srqdevg/MauiTest](url). The first and third expanders show that the label is truncated, not wrapped with variations on the grid. The second shows a variation using a horizontal stack which does not constrain the label to the contents of the expander which from my understanding of how these layouts are now meant to work is correct.

### Link to public reproduction project repository

https://github.com/srqdevg/MauiTest

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: 11 Pro Build 10.0.22621
- .NET MAUI: 7.0.81
```

**Comment by vhugogarcia** [comment]
I have tested this scenario on iOS, macOS and Android using the repository shared by @srqdevg .

I have found out the following results:
* The issue is **not** related to the **MCT Expander** control. 
* The issue occurs only when adding a HorizontalStackLayout to wrap up labels.
* This issue is already reported twice on the .NET MAUI repository. [#12415](https://github.com/dotnet/maui/issues/12415) and [#8873](https://github.com/dotnet/maui/issues/8873)
* There are a few workarounds posted on the issues mentioned such as use Grids or Formatted Labels instead.

cc @brminnick
