### ISSUE TITLE
[BUG] Picker not work correctly on popup

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hi. I have a problem with a Picker, but only on the Popup. I have already open a bug in 

https://github.com/dotnet/maui/issues/14832

But I don't know if is a Maui problem or a CommunityToolkit problem.
Can you take a look?
Thanks

### Expected Behavior

The popup should set the SelectedItem correctly

### Steps To Reproduce

Take a look to https://github.com/dotnet/maui/issues/14832, there is a repo

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPicker

### Environment

```markdown
- .NET MAUI CommunityToolkit: latest
- OS: iOS 15.7
- .NET MAUI:7
```

**Comment by cat0363** [comment]
Hi, @acaliaro 
This issue also occurred with a self-made ViewModel that does not use CommunityToolkit.Mvvm.
I created a similar ViewModel and tested it, and when I called ShowPopupAsync, the Picker's SelectedItem was initialized to null.

When I set a BreakPoint in the null case of the OnSelectedItemOutletChanged method in the source code you provided and checked the call stack, it was initialized to null at the following position. 

CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\MauiPicker.MyPopupViewModel.g.cs:45,21
    [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.2.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public global::MauiPicker.Outlet SelectedItemOutlet
    {
        get => selectedItemOutlet;
        [global::System.Diagnostics.CodeAnalysis.MemberNotNull("selectedItemOutlet")]
        set
        {
            if (!global::System.Collections.Generic.EqualityComparer<global::MauiPicker.Outlet>.Default.Equals(selectedItemOutlet, value))
            {
                OnSelectedItemOutletChanging(value);
                OnSelectedItemOutletChanging(default, value);
                OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.SelectedItemOutlet);
                selectedItemOutlet = value;
                OnSelectedItemOutletChanged(value);		// <= here
                OnSelectedItemOutletChanged(default, value);
                OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.SelectedItemOutlet);
            }
        }
    }

In order to verify whether it is initialized when the ShowPopupAsync method is called, I rewrote the provided source code as follows.

    async Task OpenPopupAsync()
    {
        var popup = new MyPopupPage();
        var ret = Application.Current.MainPage.ShowPopupAsync(popup);
        popup.BindingContext = new MyPopupViewModel();
    }

After doing the above, Outlet1 is now set to the Picker's SelectedItem.
From the above, it seems that SelectedItem is initialized when ShowPopupAsync is called.
Since this problem also occurs in the ViewModel that I created myself, there seems to be no problem on 
the ViewModel side. That's all I was able to parse.

Something seems to be happening after the ShowPopupAsync call.

**Comment by acaliaro** [comment]
Ho thanks for the answer. So, the problem is on the popup or on the picker? I have not understand...

**Comment by cat0363** [comment]
As far as I have verified, the problem seems to be on the Popup side because unintended initialization is performed after calling the ShowPopupAsync method. I have not analyzed the source code of the CommunityToolkit side, so I cannot say for sure.

**Comment by cat0363** [comment]
Hi, @acaliaro 
I found the cause and solution for this Issue problem. Next week, I will create a pull request.
The problem was in the processing of ShowPopupAsync. Could you let me handle it?

**Comment by acaliaro** [comment]
Excellent
