### ISSUE TITLE
[BUG] StatusBarBehavior not reflected on back navigation

### ISSUE THREAD

**Issue by pikausp** [CommunityToolkit/Maui#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I navigate to a page that has a `StatusBarBehavior` and then back the previous colors are kept even if the page I returned to specifies a behavior with different colors.

### Expected Behavior

The colors to change whenever a user navigates.

### Steps To Reproduce

Click the Navigate button and then navigate back

### Link to public reproduction project repository

https://github.com/pikausp/BackNavigationRepro

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: Android 13/iOS 16.4.1
- .NET MAUI: 7.0.86/7.0.100
```

**Comment by bijington** [comment]
@cat0363 thanks for you continued effort in looking at issues. I would personally say create the PR as it would likely be easier for anyone reviewing the changes to; a) review the code changes against what is currently there, and b) be able to run the sample app and validate the fix works.

**Comment by pictos** [comment]
I would say, the expected behavior is to not change the StatusBar color when we navigate back, it's not something that should be attached to a Page, but a global configuration. I can't remember an application that changes it on every navigation. If the dev wants that StatusBar color changes when navigating he should control that. We have static methods that can be called on the `NavigateTo/NavigateFrom` methods.

**Comment by pikausp** [comment]
> I would say, the expected behavior is to not change the StatusBar color when we navigate back, it's not something that should be attached to a Page, but a global configuration. I can't remember an application that changes it on every navigation. If the dev wants that StatusBar color changes when navigating he should control that. We have static methods that can be called on the `NavigateTo/NavigateFrom` methods.

@pictos page A has a style, page B has a different style. Would you say it makes sense for the page A to have the style of Page B when returned to?

I could understand if you wanted a property on the behavior to activate this behavior, but I think it's a reasonable request/expectation.

**Comment by cat0363** [comment]
@bijington, Thank you for your reply. I think everyone has their own opinion, so I'll wait for the judgment.
@pictos , I agree with you. Since the StatusBar represents the state, if the state changes arbitrarily due to page 
transitions, it will be an unintended change, right? The state represented by the StatusBar changes depending 
on the way of thinking, but if you ask me whether it is per page or per application, I think it is the latter.

**Comment by bijington** [comment]
I agree with @pikausp. I expect the status bar to change when the page the behavior is attached to becomes visible. So effectively the `OnAppearing` logic

**Comment by pikausp** [comment]
> if the state changes arbitrarily due to page transitions, it will be an unintended change, right?

@cat0363 but that already happens when you navigate to a page with the discussed behavior...

**Comment by cat0363** [comment]
Hi, @pikausp 
My fix only changes the size of the status bar on screen rotation, not the color. The fix for Issue #1193 does not affect this issue.

**Comment by ryanlpoconnell** [comment]
Agree with @pikausp & @bijington, because whenever the status bar color is set, it affects the app globally, the status bar color needs to be reapplied each time a page becomes *visible, including on back nav.

One slight concern I have is on the definition of whether we really mean OnAppearing or just whenever a page becomes the current visible page...  I say this because I've experienced differing lifecycles over the years where OnAppearing event under certain situations does or doesn't get fired.  E.g. not fired when navigating between tabs or after popping back

**Comment by Cybrosys** [comment]
I would like to also bring up that there is an issue with it on Android 10. As mentioned in issue #1466. Where navigating between previously visited shell tabs does not update the status bar style; `OnAttachedTo` is called each time a tab is changed. 

The color and style is however updated correctly when I tested it on Android 13 (I did not test the back navigation scenario described here).

Implementing setting the color and style in `OnAppearing` results in the desired behavior, which I'm guessing is the equivalent to subscribing to the event `NavigatedTo` and performing the color and style calls there (https://github.com/CommunityToolkit/Maui/issues/1194#issuecomment-1590731555).
