### ISSUE TITLE
[BUG] Sample project build error

### ISSUE THREAD

**Issue by b-pattanayak** [CommunityToolkit/Maui#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

while took  latest from main branch  and build sample project getting build errors missing extension methods
pages/ converters , TextCenterVertical() and .TextCenter() methods are missing
![image](https://github.com/CommunityToolkit/Maui/assets/135239564/225d5edf-b7f4-40a1-9bf7-7dbf02431024)

### Expected Behavior

extension methods should be available and build should be success 

### Steps To Reproduce

take latest from main branch and build sample project

### Link to public reproduction project repository

this is simple build issue

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by brminnick** [comment]
Unable to reproduce

**Comment by VladislavAntonyuk** [comment]
make sure you built SourceGenerators

**Comment by Kapusch** [comment]
Since I upgraded `CommunityToolkit.Maui.Markup` from `v3.0.0` to `v4.0.0`, I have this IntelliSense issue on Visual Studio For Mac
<img width="522" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/9576733/71198384-7dec-476b-a93a-5783a1486331">

Although this is same error code `CS1061`, this isn't preventing build or execution to work

**Comment by brminnick** [comment]
@Kapusch Which IDE are you using in this screenshot?

The `TextCenter()` extension methods are auto-generated using Source Generators. It could be that your IDE hadn't auto-generated the `TextCenter` code before running the intellisense analyzers.

**Comment by Kapusch** [comment]
It's on Visual Studio Community 2022 For Mac v17.6.7

It was just a remark like it was working well with `CommunityToolkit.Maui.Markup v3.0.0`...
<img width="1237" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/9576733/901a6198-7148-49a4-b8eb-8cf7b5598931">

... but not anymore with v.4.0.0 ^^

I didn't test in VS Code how it behaves, I don't know if there is any IntelliSense there by the way.

**Comment by brminnick** [comment]
Ah - yea, that makes sense. VS for Mac is usually late to get all of the Roslyn updates. 

I switched to Jet Brains Rider from VS for Mac after Microsoft announced they're deprecating VS for Mac, and I haven't sen this problem in Rider.

It could also be that we need to push out `CommunityToolkit.Maui.Markup v4.0.1`; in our Source Generator, [we updated it to use the latest version of `Microsoft.CodeAnalysis.CSharp v4.8.0`](https://github.com/CommunityToolkit/Maui.Markup/commit/7ac435ccd5e54873942494cfbf3f205619a290af), but haven't yet released an update to `CommunityToolkit.Maui.Markup` since. 

Let's keep an eye on it for now, but I have a hunch that it may be resolved in a future VS for Mac update. If the next VS for Mac update doesn't fix it, let me know and we'll publish `CommunityToolkit.Maui.Markup v4.0.1` to see if that fixes the problem!
