### ISSUE TITLE
[BUG] Cannot resolve type IsEqualConverter when used in a library project

### ISSUE THREAD

**Issue by awalker-dsg** [CommunityToolkit/Maui#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using Visual Studio (VS) to build a MAUI library that contains a reference to the MAUI community toolkit's IsEqualConverter, the following error is displayed in the VS Output window:

`XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:mct:IsEqualConverter".`

This issue occurs for other MCT converter classes as well. 

The same (or very similar) issue was reported in [.NET MAUI issue 12642](https://github.com/dotnet/maui/issues/12642). However, that ticket was closed on 13 Jan by jfversluis based on an earlier post to the ticket that said this:

    You need this in your MauiApp class:
  
    var builder = MauiApp
             .CreateBuilder()
             .UseMauiApp<App>()
             .UseMauiCommunityToolkit() <---

    Funny because that feels like a runtime thing, not a compile-time thing, but it solves the problem.

The problem is that libraries don't have a MauiApp class, so the solution suggested in [issue 12642](https://github.com/dotnet/maui/issues/12642) will not work here.

This issue was discovered while migrating a Xamarin library project to MAUI. 

### Expected Behavior

When a MAUI library project is built, references to MAUI Community Toolkit converter classes are resolved.

### Steps To Reproduce

1. Open the solution from the repro repository in Visual Studio.
2. Attempt to build the project. If the problem exists, an `XamlC error XFC0000: Cannot resolve type` error will be reported in the VS Output window for each target platform.

### Link to public reproduction project repository

https://github.com/awalker-dsg/MauiLibTestLib_ConverterIssue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Windows 11
- .NET MAUI: VS 17.6.33723.286
```

**Comment by brminnick** [comment]
The [linker](https://learn.microsoft.com/en-us/dotnet/maui/deployment/visual-studio-properties?view=net-maui-7.0#build-1) is removing our library from your project. This happens when the compiler removes "unused" third-party libraries and it happens because the linker isn't intelligent enough to understand that the library is being used in XAML (it only knows how to scan C# code).

<img width="868" alt="image" src="https://user-images.githubusercontent.com/13558917/228353886-277dd0a2-74b9-4bf0-8c5f-95479b7b1004.png">

### Workaround

Update the following code in `MainPage.xaml` to add `x:Name` which will generate a C# property for the Behavior in your code-behind; during compilation, the linker will now see that you are using `CommunityToolkit.Maui` and will no longer remove it:

```xaml
<toolkit:IsEqualConverter x:Name="IsEqualConverter"/>
```

**Comment by MalmoIt** [comment]
Experience similar issue with Expander in XAML. 

Resolved it by adding : 

`var ignoreMe = typeof(Expander);`

in the code-behind.
