### ISSUE TITLE
[BUG] [Popup][Android] HorizontalTextAlignment Not working

### ISSUE THREAD

**Issue by BaY1251** [CommunityToolkit/Maui#1450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

As shown in the figure,HorizontalTextAlignment Not working
This issue only occurs on Android devices, and Windows performs normally.

### Expected Behavior

HorizontalTextAlignment Same performance as ContentPage

### Steps To Reproduce

1. Open Toolkit\ Toolkit.sln
2. Click the button to reproduce the problem

Popup has the same layout as the page, but its performance is inconsistent!

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:6.0.0
- OS:Android 7.1
- .NET MAUI: 7.0.96 SR8
```

**Comment by brminnick** [comment]
Hi @BaY1251! Could you please edit the description and fix your `Steps To Reproduce`? I don't see `Toolkit.sln` in the [`public reproduction project repository` you linked](https://github.com/BaY1251/MauiDebug.git).

**Comment by BaY1251** [comment]
@brminnick  Toolkit\ Toolkit.sln  Just uploaded

**Comment by cat0363** [comment]
By modifying it as shown below, you can get the desired result, but there is a problem.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]

    static void CalculateSizes(IPopup popup, Context context, Size windowSize, ref int realWidth, ref int realHeight, ref int realContentWidth, ref int realContentHeight)
    {
        ArgumentNullException.ThrowIfNull(popup.Content);

        var density = context.Resources?.DisplayMetrics?.Density ?? throw new InvalidOperationException($"Unable to determine density. {nameof(context.Resources.DisplayMetrics)} cannot be null");

        if (popup.Size.IsZero)
        {
            if (double.IsNaN(popup.Content.Width) || double.IsNaN(popup.Content.Height))
            {
                var size = popup.Content.Measure(windowSize.Width / density, windowSize.Height / density);
                realContentWidth = (int)context.ToPixels(size.Width);
                realContentHeight = (int)context.ToPixels(size.Height);

                if (double.IsNaN(popup.Content.Width))
                {
                    realContentWidth = popup.HorizontalOptions == LayoutAlignment.Fill ? (int)windowSize.Width : realContentWidth;
                }
                if (double.IsNaN(popup.Content.Height))
                {
                    realContentHeight = popup.VerticalOptions == LayoutAlignment.Fill ? (int)windowSize.Height : realContentHeight;
                }
            }
            else
            {
                realContentWidth = (int)context.ToPixels(popup.Content.Width);
                realContentHeight = (int)context.ToPixels(popup.Content.Height);
            }
        }
        else
        {
            /* Before fix
            realWidth = (int)context.ToPixels(popup.Size.Width);
            realHeight = (int)context.ToPixels(popup.Size.Height);

            var size = popup.Content.Measure(popup.Size.Width, popup.Size.Height);
            realContentWidth = (int)context.ToPixels(size.Width);
            realContentHeight = (int)context.ToPixels(size.Height);
            */
            // After fix
            realWidth = (int)context.ToPixels(popup.Size.Width);
            realHeight = (int)context.ToPixels(popup.Size.Height);
            realContentWidth = realWidth;
            realContentHeight = realHeight;
        }

        realWidth = Math.Min(realWidth is 0 ? realContentWidth : realWidth, (int)windowSize.Width);
        realHeight = Math.Min(realHeight is 0 ? realContentHeight : realHeight, (int)windowSize.Height);

        if (realHeight is 0 || realWidth is 0)
        {
            realWidth = (int)(context.Resources?.DisplayMetrics?.WidthPixels * 0.8 ?? throw new InvalidOperationException($"Unable to determine width. {nameof(context.Resources.DisplayMetrics)} cannot be null"));
            realHeight = (int)(context.Resources?.DisplayMetrics?.HeightPixels * 0.6 ?? throw new InvalidOperationException($"Unable to determine height. {nameof(context.Resources.DisplayMetrics)} cannot be null"));
        }
    }

[After fix]
<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/980fa9e2-b148-4740-9dde-5c0ae3d8ad9b" />

[Before fix]
<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/ee49b2ca-628f-4f19-b9fb-371ee54e9e0d" />

Originally, I would like it to work with the Before fix code that is commented out, but since VerticalTextAlignment will not work correctly when Measure is called, I have no choice but to use the After fix code.

A problem occurs when only the HeightRequest of the Popup's Content is specified without specifying the Popup's Size.

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/09e38138-0420-4b67-97fd-7d2a2ae97996" />

If you call the method below, the layout below the Popup's Content will not be drawn correctly.

    var size = popup.Content.Measure(windowSize.Width / density, windowSize.Height / density);

Originally, the Label's VerticalTextAlignment is reflected and the Label's Text should be displayed in the Center, but it is displayed in the Top.

If you could just calculate the size without redrawing, you might be able to solve this problem, but as far as I've researched, there's no way to do that.

**Comment by cat0363** [comment]
This issue is similar to the issue below.
https://github.com/dotnet/maui/issues/2019

When I tried getting the platform-side View and calling the parent's Measure method and 
child's Measure method, it was displayed as intended. By the way, I tried calling the child's 
Measure method only when the child was AppCompatTextView, as described in the PR that 
corrected the issue above.

Below is the execution result.

https://github.com/CommunityToolkit/Maui/assets/125236133/367df8d5-5c87-4469-a3cc-527da1ac6920

It seems that only for Labels, the Measure method must be called intentionally.
If there is no problem, I will create a PR.

**Comment by cat0363** [comment]
In addition to fixing this issue, I would like to fix the size measurement logic when 
only either WidthRequest or HeightRequest on the Popup Content side is specified 
when the Popup Size is not specified on iOS, Android, or Windows. This case was 
not well thought out.
