### ISSUE TITLE
[BUG] CommunityToolkit.Maui.Views.Popup Button Text Alignment

### ISSUE THREAD

**Issue by alaskanrogue** [CommunityToolkit/Maui#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If a popup appears after restoring the application from a background state, the button text is aligned to the left where the text is centered if the popup is created while the application is in a foreground state.

Foreground
![image](https://github.com/CommunityToolkit/Maui/assets/14001196/3deb06ae-cc59-44a5-85ae-a8591cd28f4d)

Background
![image](https://github.com/CommunityToolkit/Maui/assets/14001196/e2a2d633-3bb1-44bb-8dae-9478d5ff323f)

### Expected Behavior

Button text aligned center.

### Steps To Reproduce

1. 1. Create a simple Android application which can create a popup and is designed to operate in a background state as while as foreground.
2. Trigger the popup appearance after a short period of time, i.e., 10 seconds, so that there is sufficient time to move the application to the background and activate the popup appearance after the background state is entered.

### Link to public reproduction project repository

https://github.com/cat0363/MauiComm-IssueForeBackChange

### Environment

```markdown
.NET 7.0.96

ios 16.4.8968-net8-rc2/8.0.100-rc.2
android 34.0.0-rc.2.468/8.0.100-rc.2

.NET MAUI 6.0

VS 17.8.34219.65
```

### Anything else?

NA

**Comment by cat0363** [comment]
@bijington , I created a reproduction code. I will upload it below.
https://github.com/cat0363/MauiComm-IssueForeBackChange.git

Below is the execution result of version 6.0.0.

https://github.com/CommunityToolkit/Maui/assets/125236133/6ea12b01-a1c9-4a0b-b08c-dc89581fcb0e

Below is the execution result of version 6.1.0.

https://github.com/CommunityToolkit/Maui/assets/125236133/c22d2598-655a-483f-bec5-229612c13bc9

Version 6.0.0 reproduces the reporting issue, but version 6.1.0 does not reproduce the reporting issue.
My reproduction code may be wrong, so please use it as a reference only.

**Comment by alaskanrogue** [comment]
@cat0363 Great that you were able to find and resolve the issue.  I also created a reproduction project: https://github.com/alaskanrogue/CriticalPopup. I look forward for verification of resolution.

**Comment by cat0363** [comment]
@alaskanrogue , The above link is a 404 error.
Could you please check the access rights of the repository?

**Comment by cat0363** [comment]
I have confirmed that the repro code I created is different from the repro code you provided, and that the problem also occurs in version 6.1.0.

**Comment by cat0363** [comment]
I don't know if it's the same as the following, but it's similar in terms of the alignment of the button text.

https://github.com/dotnet/maui/issues/14712

When the text of the button in the Popup is not centered, it is necessary to check whether the screen is rotated to update it. If this is the same problem, I need to see if it can be solved in .NET 8.

**Comment by alaskanrogue** [comment]
@cat0363 I agree, it appears that rotation while in the background centers the text, however on the rotated phone while totally in the foreground the issue continues to exist.

**Comment by cat0363** [comment]
@alaskanrogue , Below is the workaround I came up with.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="CriticalPopup.AuthorizationPopup">
        <VerticalStackLayout>
            <Label x:Name="PopUp" BackgroundColor="White" TextColor="Black" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Center" />
            <Button x:Name="Button_Continue" BackgroundColor="Red" TextColor="White" FontSize="Large" Clicked="OnShowDestination" SizeChanged="Button_Continue_SizeChanged"/>
        </VerticalStackLayout>
    </toolkit:Popup>

Try adding the button's SizeChanged event and implementing the following.

    private void Button_Continue_SizeChanged(object sender, EventArgs e)
    {
        var button = (sender as Button);
        button.HeightRequest = button.Height;
        button.WidthRequest = button.Width;
    }

The label should now be centered even when rotated in the background.

**Comment by alaskanrogue** [comment]
The workaround was successful. The application tested on is locked in portrait mode however, so I was not able to test the landscape mode. It did work in the reproduction app also but rotating had an expected impact of resizing and that was subsequently maintained when the app returned to portrait.

**Comment by cat0363** [comment]
I now understand what mechanism is causing this problem.
In conclusion, on Android, the button size does not reflect LayoutOptions.
For this reason, the button size is set to the minimum size necessary to display the button.
The reason why the Button's text appears to be closer to the right edge is because it is only as large as necessary to display the Button's text.

The size required to display the Popup is determined by calling the platform's Measure method.
However, for Android only, it seems necessary to call the Measure method strictly taking into consideration the LayoutOptions on the VirtualView side.

Below are the verification results.

https://github.com/CommunityToolkit/Maui/assets/125236133/b8d5c49a-3096-4573-b28a-3f83e48cb83b

Below are the verification results before and after rotating the device.

[Before Rotation]

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/ece4c5a5-21c7-4a2a-81e1-782239aaef0a" />

[After Rotation]

<img height="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/d42dca29-1ec5-40aa-bd0c-7ac5f491b517" />

Various patterns must be tested and large-scale modifications are required.

It would be best if the layout could be updated on the VirutalView side, but it is very troublesome because the layout needs to be updated on the PlatformView side. It looks like it will take some time to fix it.

**Comment by cat0363** [comment]
I forgot to mention that this issue has nothing to do with [#14712](https://github.com/dotnet/maui/issues/14712). Therefore, even if it is updated to .NET 8, it will not work as intended.

**Comment by cat0363** [comment]
I will create a PR regarding this matter soon.
I was able to write the fix code, but I've been busy with my day job and haven't been able to create a PR.

**Comment by vallgrenerik** [comment]
Im also facing this issue! 
Thank you @cat0363 for fixing this! ⭐
