### ISSUE TITLE
Please Don't forget the AppBar feature

### ISSUE THREAD

**Issue by jingliancui** [CommunityToolkit/Maui#15]
https://github.com/xamarin/XamarinCommunityToolkit/issues/545

I remember this feature is still pending .

**Comment by jfversluis** [comment]
We'll reevaluate anything and everything that is in the Toolkit now and what we were thinking of adding.

Closing this one so we don't have duplicate issues on both sides.

**Comment by brabebhin** [comment]
Hi,

What is the status of this?
A proepr toolbar is a must for MAUI. The current shell UI looks like something from the 1800s. Even the defunct windows phone had such basic functionality. 10 years ago.

**Comment by jfversluis** [comment]
@brabebhin I appreciate your feedback, but I don't really see any need to talk bad about anyones work. It might not have been your intention, but adding remarks like "looks like something from the 1800s" and "even the defunct windows phone [...] 10 years ago" doesn't really give off a good vibe.

We don't have any [open proposal](https://github.com/CommunityToolkit/Maui/projects/1) for it yet, if you're up for the challenge, feel free to open one and start working on it.

**Comment by brabebhin** [comment]
Sorry if my intention sounded bad. I really like bombastic descriptions of things. Especially when the situation is bad. But the reality is, MAUI is missing basic UI components that make up today's UI patterns. Which is why people (including your own company may I add) is running as far as possible from MAUI.

Closing, moving, reopening, duplication this kind of requests for basic functionalityf from the community makes the MAUI framework look bad, abandoned, directionless. So there goes the good vibes.

I will reopen this suggestion again, hopefully the 4th time is the charm :)

**Comment by jfversluis** [comment]
> I will reopen this suggestion again, hopefully the 4th time is the charm :)

That isn't what I proposed. I don't think opening it a fourth time will make it better. This is a community toolkit. It's being worked on by people outside of the normal working hours. There is a lot of stuff that we want to port and this one in particular is a big effort.

Unless there is someone who is going to open a detailed proposal and is committing to working on it, I don't think it will happen in the very near future. If this is something you want and need, please consider donating some of your expertise and time to help us, yourself and everyone else out.

I don't think I need to go into the rest you mentioned. I disagree as is probably obvious. I hope you want to be part of making it better and not just dropping your bombastic descriptions. Thanks!

**Comment by brabebhin** [comment]
I don't think this should be part of the community toolkit, but rather part of the main MAUI framework, becuase this is such a basic functionality. I will probably roll my own implementation (for windows and android, won't be able to touch apple devices due to their ancient babylon style walled garden).

**Comment by jfversluis** [comment]
Again, this is a very big feature that we probably want to test out first and the Toolkit is an amazing place for that. And, mind you, you are posting all of this in the Toolkit repo, that's why I assumed you were talking about this.

While you might think this is basic functionality, others might think otherwise. If we were to implement everything that someone thinks is basic functionality _then_ we would be directionless. I'm not saying that all of this is true in this case, maybe it will be done, but we don't have any immediate plans for it right now, at least not for .NET MAUI directly simply because or data shows other priorities right now.

Another option you might want to look at is Sharpnado which has some great controls. Good luck!

**Comment by brabebhin** [comment]
I had a look at the monumental architecture of Maui and you are partially right. This isn't easy to do since the change has to be operated in the middle of the inheritance hierarchy.

At most, it is possible to move the existing toolbar to the bottom or the sides. This could be done with handlers snd not require recreating the entire MAUI page inheritance.

Ofc we could slice and dice our way in,  but we gotta keep that monument architecture somewhat intact.
