### ISSUE TITLE
[BUG] Popup - Size is not respected in Landscape mode on iOS

### ISSUE THREAD

**Issue by VNGames** [CommunityToolkit/Maui#1604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

There was an issue open for this but it was closed even though it wasn't fixed.
https://github.com/CommunityToolkit/Maui/issues/843
It was closed by this but there was no screenshot of testing on iOS landscape. Nobody tested the original issue in that PR but closed it as fixed.
https://github.com/CommunityToolkit/Maui/pull/1320

```
<toolkit:Popup
    x:Class="MauiApp2.Popup1"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    CanBeDismissedByTappingOutsideOfPopup="true">
    <ContentView BackgroundColor="Aqua">
        <Label
            Margin="50"
            Text="Popup content" />
    </ContentView>
</toolkit:Popup>
```
In Portrait
![image](https://github.com/CommunityToolkit/Maui/assets/17302712/69b361dd-fbaa-4973-be9f-abf4b5b0600b)
In Landscape
![image](https://github.com/CommunityToolkit/Maui/assets/17302712/d29abcfc-1966-410d-8ee2-b6f431debcd5)

If I do this (setting layout options)
```
    <ContentView BackgroundColor="Aqua" VerticalOptions="Center" HorizontalOptions="Center">
        <Label
            Margin="50"
            Text="Popup content" />
    </ContentView>
```
It looks like this
![image](https://github.com/CommunityToolkit/Maui/assets/17302712/933ead44-b5c1-4c5c-9384-bd6f02c65a04)

Color around is the color of a Popup.
If I set it to Transparent it would look like this which is how it should be looking but in such case tapping outside of popup content won't work since that area is still a popup and not a dimmer.
![image](https://github.com/CommunityToolkit/Maui/assets/17302712/407599da-d794-4ec2-b869-916d36964d17)

Here is the project to reproduce
[Popup.zip](https://github.com/CommunityToolkit/Maui/files/13696530/Popup.zip)

### Expected Behavior

Popup open with the correct size like it does in Portrait mode. Tapping outside the popup closes it if `CanBeDismissedByTappingOutsideOfPopup="true"`

### Steps To Reproduce

1. Open app 
2. Rotate it into Landscape mode
3. Tap on "Click me"

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- .NET MAUI: 8.0.3
```

**Comment by VNGames** [comment]
I am not gonna trash my github account with repro projects because you are scared to open zip. Create a virtual machine and open it there if you all are so scared

**Comment by bijington** [comment]
@VNGames a couple of things:
1. Most of us are not Microsoft employees and none of us are paid or reimbursed in anyway by Microsoft for the effort on this toolkit. We are all volunteers contributing our own free time to building this toolkit for the community.
2. Our contributing guide that you ticked as having read states that we ask for a reproduction in the form of a repository and why we do so.

If you do find time to upload your project to GitHub or GitLab and share the link then great, otherwise I'm happy to let the bot close this down.

**Comment by VNGames** [comment]
@bijington Didn't know Microsoft aren't backing this up. In any case me creating a bug report is a contribution as well and doing contributions like that shouldn't be as hard as possible because otherwise nobody will report bugs. Making a repo instead of a zip is a headache. Nobody is going to send viruses here. My bug report is not for me because bug fixes take years usually on Xamarin/MAUI and ofc I will not wait for a fix and will use some workaround instead. I am doing this for people that come after me. The goal of a project is to be normal and bug free. Git repo policy is a huge obstacle for that. There is no need for a git repo per each bug. Next time I see a bug and can create a simple clean repro project, will I do that? no ofc because I will know that I need to create a git repo. That's why a lot of bugs will be just living there unreported by people just because of some paranoia of viruses. 

Reopen this. it has repo project https://github.com/CommunityToolkit/Maui/issues/843

**Comment by jfversluis** [comment]
@VNGames we have very clearly described why it is that we ask for reproductions this way, and yes, people are sending viruses this way. It is clear that you don't disagree, then let's agree to disagree.

Personally I find it a bit disappointing that we have to discuss these logistics instead of focussing on the real problem: the issue at hand. And even more so: that you are working on a workaround that, from how I understand it, you are going to add to your own project. I think the main idea of open-source, at least this project, is that we are in this together. It's the _community_ toolkit.

Now you know that none of us are getting paid to do this, we do this because we love what we do and want to make the .NET MAUI ecosystem better. You get to use that, for free, no questions asked. In that light, it would be amazing if you could contribute your fix back so other can benefit. But at the very least, I think the least you could do is show some respect for that and not doubt our methods here.

I am going to end this discussion here, I think all has been said. I will reopen the other issue if that has more information in the form of a reproduction. Thank you for bringing this to our attention.
