### ISSUE TITLE
[BUG] [Android]memory leak when "recursively" calling ShowPopup?

### ISSUE THREAD

**Issue by BaY1251** [CommunityToolkit/Maui#1652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When recursively calling ShowPopup, memory continues to increase, and even frequent 'GC.Collect' will not improve.
The running speed slows down until ANR occurs

PS;
It's not true recursion, Implementing recursive operations through delayed asynchronous calls

### Expected Behavior

Normal

### Steps To Reproduce

Open MauiComm-IssuePopupLeak\MauiComm-IssuePopupLeak.sln
Click 'Show' 

### Link to public reproduction project repository

https://github.com/BaY1251/MauiComm-IssuePopupLeak.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.1
- OS:Android7.1
- .NET MAUI:8.0.6
```

**Comment by bijington** [comment]
I'm not really sure what the sample application is trying to prove. If you do something recursively the applications memory consumption will always increase because you are increasing the call stack. The application is doing that pretty quickly too roughly every 110ms by my understanding.

You will also reach an ANR (assuming application not responding) because your looping logic never ends and therefore your code will continue to execute for eternity

**Comment by BaY1251** [comment]
The recursion here is not true recursion. 
If you have time, please take a look at the code first.
Without using Popup, memory will not continue to increase

**Comment by bijington** [comment]
You are correct about it not being real recursion, I see you are dispatching the call to the current method so that won't increase the stack. Apologies I missed that detail.

When you say without using Popup the memory usage won't increase, what are you using instead to compare it to?

I did read the code and I stand by my comment that the code will never complete. I noticed that there is a comparison to `maxShowCount` in the uncompiled #if directive above. Did you mean to include that inside AutoStart?

**Comment by BaY1251** [comment]
> When you say without using Popup the memory usage won't increase, what are you using instead to compare it to?

I use a very primitive way to check memory changes every hour:
`adb shell top -n 1 | findstr "\<com.companyname.mauicomm_issuepopupleak\>"`


> I did read the code and I stand by my comment that the code will never complete. I noticed that there is a comparison to in the uncompiled #if directive above. Did you mean to include that inside AutoStart?`maxShowCount`

it is the code written by cat0363, a way of using a timer.Not applicable to my actual usage environment, and I mistakenly deleted several variables.

**Comment by cat0363** [comment]
There is a mistake in the code I wrote. The variable popup should be initialized to null, but it is not. If you call GC, you should also initialize the variable popup to null.

**Comment by bijington** [comment]
Thanks both!

Do we still believe there is a memory leak with Popup?

**Comment by cat0363** [comment]
@bijington , I don't know at this point if it exists or not because I haven't taken the time to research it.

**Comment by bijington** [comment]
No problem! I'm happy to dig around and see what I can find too.

**Comment by BaY1251** [comment]
Memory is indeed constantly increasing...
Perhaps ' initialize the variable popup to null' and GC will take effect, but frequent calls in production environments may not be appropriate

**Comment by BaY1251** [comment]
I try with 'Drastic.LeakCanary', No leak report.Popup may not be suitable for frequent calls. Thanks all

**Comment by bijington** [comment]
Thanks for the update. It's safe to say the current test of showing one every 100ms is not a valid use case in an app. How frequently would you say you currently show one?

**Comment by BaY1251** [comment]
My app used for long-distance check-in countdown, usually lasting over 10 seconds, sometimes requiring configuration to be less than 1 second

**Comment by vhugogarcia** [comment]
Thanks @BaY1251 for the feedback. If you are not seeing memory leak issues with the Popup, could you please confirm with us? so, we can close the issue.

Thanks again 😃

**Comment by vhugogarcia** [comment]
Thanks @BaY1251 for confirming the information about the memory leak. I am closing this issue since it mainly focuses on the memory leak.

**Comment by BaY1251** [comment]
PS: Alerts.Toast also has the same problem, I solved it using Android native.
`Android.Widget.Toast.MakeText("...").Show()`
