### ISSUE TITLE
[BUG] Application crashes when pressing Tab+Spacebar while video is playing using CommunityToolkit.Maui.MediaElement on Windows platform

### ISSUE THREAD

**Issue by SanthoshAthili3101** [CommunityToolkit/Maui#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The application crashes immediately upon pressing the "Tab" key and the "Spacebar" key simultaneously while the video is playing. The crash occurs consistently, and no error message or exception is displayed to the user.

### Expected Behavior

The application should handle the key press combination without crashing, and the video playback should continue uninterrupted.

### Steps To Reproduce

1. Launch the .NET MAUI application on a Windows platform.
2. Navigate to the screen where a video is displayed using the MediaElement control.
3. Start playing the video.
4. While the video is playing, press the "Tab" key and the "Spacebar" key simultaneously.

### Link to public reproduction project repository

NA

### Environment

```markdown
- .NET MAUI CommunityToolkit:2.0.0
- OS: Windows
- .NET MAUI:7
```

**Comment by olekssokol** [comment]
Hi @SanthoshAthili3101, I have managed to reproduce this in the CommunityToolkit.Maui.Sample project. In my case, this happens only when the "Tab" key switches the active state to the "Change Aspect" button, and then the "Space" key executes it. 
In this case, the problem is due to the DisplayActionSheet call from the Microsoft.Maui.Controls package, it should display the window and return the pressed button, but instead of the window, it immediately returns null, which was not handled in the Sample project. I fixed it at the project level in my branch (1863-bug-application-crashes), but this is an issue in Maui.Controls of older versions and in 8.0.21 everything works without crash.

If you are experiencing the issue in a different way, please provide details so I can help you.
