### ISSUE TITLE
[BUG] After upgrading CommunityToolkit.Maui from 9.0.3 to 9.1.0,in ios app crash is observed on App start.

### ISSUE THREAD

**Issue by ketakidevendra** [CommunityToolkit/Maui#2282]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Upgrading the CommunityToolkit.Maui package from 9.0.3 to 9.1.0 results in the app crashing at startup in iOS due to System.TypeLoadException has been thrown, Could not set up parent class, due to: Invalid generic instantiation assembly:.

I am using VS 17.11.5
Framework - .Net 8

### Expected Behavior

App should not crash in iOS with MAUI toolkit nuget package version - 9.1.0

### Steps To Reproduce

1. Upgrade VS to latest available version.
2. Xcode is 15.4
3. Run app in iOS platform in debug/ release mode.
4. App crashes on start.

### Link to public reproduction project repository

https://github.com/ketakidevendra/ToolbarItemBindingIssue

### Environment

- .NET MAUI CommunityToolkit: 9.1.0
- OS: iOS 17.5
- .NET MAUI: 8.0
- XCode 15.4

### Anything else?

Workaround - Downgrade to 9.0.3 works without crash.

**Comment by leo-tau** [comment]
@ketakidevendra 
You would like to say "Downgrade to 9.0.3". This workaround worked also for me

**Comment by theresaWalsh** [comment]
Also encountering this

**Comment by brminnick** [comment]
We closed it because we cannot reproduce this error.

This is most likely a misconfiguration of your local environment. Please open a new Issue with a reproduction sample if you are unable to resolve your problem.

@amilici  Please ensure you have installed the following items:
- [ ] Xcode 16.0.0
- [ ] Update to the latest stable version of Visual Studio (or Jet Brains Rider)
- [ ] Download/install the [latest stable version of .NET 8 (v8.0.403)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
- [ ] After installing .NET SDK v8.0.403, update to the latest stable version of .NET MAUI
  - On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
  - On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`
- [ ] Add a [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to your application with the following parameters to ensure you're not using a unsupported preview version of .NET:

### global.json
```
{
  "sdk": {
    "version": "8.0.403",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}

```

**Comment by bebe84** [comment]
I have the same problem, nothing really helps. Even when I am downgrading to 9.0.3 app still crashes on startup.

**Comment by giannistek1** [comment]
Most people solve this problem by updating their .NET 8 SDK version. Should be version **v8.0.403**.  This version is compatible with the latest CommunityToolkit.

This also solved this error for me, but I also updated the MAUI workload just in case.

See this issue as well:
https://github.com/CommunityToolkit/Maui/issues/2148

**Comment by bebe84** [comment]
Yes, I can confirm, v8.0.403 worked for me (with installing newest workload) and app is no longer crashing.

**Comment by vhugogarcia** [comment]
Thanks @giannistek1 and @bebe84 for confirm it works now.
