### ISSUE TITLE
MaskedBehavior Cursor jumps to end on editing text

### ISSUE THREAD

**Issue by LeoJHarris** [CommunityToolkit/Maui#2301]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The mask jumps when editing/removing or adding text

https://github.com/user-attachments/assets/dd6106dc-ea97-49c1-bb6d-bb881f77ef28

### Expected Behavior

The mask should not update and remove text or add text where the cursor is without jumping

### Steps To Reproduce

1. Open sample an type into the entry field.
2. Attempt to remove characters and adding new ones in each of the segments of the masked input

### Link to public reproduction project repository

https://github.com/LeoJHarris/CommunityToolkit_JumpingMaskBehavior.git

### Environment

Toolkit 9.1.0
Android 34
MAUI 8.0.92

See project sample for details.

**Comment by vhugogarcia** [comment]
Hi @LeoJHarris, thanks so much for providing the details of the issue you're encountering! I just wanted to let you know that this seems to be a recurring issue within .NET MAUI.

Here are a couple of related issues that might be of interest:
- [Issue #6916](https://github.com/dotnet/maui/issues/6916)
- [Issue #22497](https://github.com/dotnet/maui/issues/22497) _(which you recently commented on as well)_

The behavior you're describing, specifically regarding cursor placement in the entry, is managed by .NET MAUI, not the Community Toolkit. Since there is already an open issue in the .NET MAUI repository, I’d recommend following it there. You might also find some insights in the [EditTextExtensions.cs file](https://github.com/dotnet/maui/blob/e3f3f0bbbe2860f953fad8a9e38f5f4037cd52fd/src/Core/src/Platform/Android/EditTextExtensions.cs#L332), as this is where the .NET MAUI extension handles it.

There have been a few PRs addressing this cursor issue in .NET MAUI, for example, [PR #15099](https://github.com/dotnet/maui/pull/15099). Additionally, someone shared a potential workaround that might help you resolve the issue: [Workaround posted here](https://github.com/dotnet/maui/issues/11313#issuecomment-1336491257).

Given that this falls outside the scope of the Community Toolkit, I’m going to close this issue. I hope this helps, and feel free to follow the .NET MAUI issue for updates!

Thanks again for bringing this up! 😊
