### ISSUE TITLE
[BUG] Toast Faults on Windows

### ISSUE THREAD

**Issue by david-maw** [CommunityToolkit/Maui#2356]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

In .NET 9 invoking Toast on Android works fine but doing it on Windows throws an exception with a multi line error of:
```
Element not found.

Element not found.
```

### Expected Behavior

A Toast notification rather than an exception on Windows.

### Steps To Reproduce

Clone the repo then build and run the app on Windows, Once it is running click the button and you should see the fault.

### Link to public reproduction project repository

https://github.com/david-maw/Community-Toast.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.1.1
- OS:Windows 11
- .NET MAUI: 9.0.10
```

**Comment by brminnick** [comment]
We do not yet support .NET 9.

We are blocked from merging any PRs until we are able to merge our [.NET 9 PR](https://github.com/CommunityToolkit/Maui/pull/2215) which is currently blocked by a bug in .NET MAUI. 

Once the MAUI engineering team resolves this bug, we will be unblocked and can resume merging PRs for the Community Toolkit: https://github.com/dotnet/maui/issues/25871

This Issue is fixed by https://github.com/CommunityToolkit/Maui/pull/2215

**Comment by david-maw** [comment]
Thanks, and sorry, I hadn't realized that .NET 9 wasn't supported yet.
