### ISSUE TITLE
[Bug] MacCatalyst SelectAllTextBehavior on Editor

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#432]
On MacCatalyst apps, when you focus on the (Maui)`Editor` control, the text doesn't show selected. It selects all the text as we want, but right after the system put the cursor in the place that the user did the click, more info in this issue

- https://github.com/xamarin/xamarin-macios/issues/15156

The plan is to discover a way to work around this behavior or find the _correct way_.

**Comment by vhugogarcia** [comment]
Hello @pictos and @brminnick ,

After reviewing this issue in-depth on my side. I found the following bits:
- Per our friend Rolf at the [xamarin-macios](https://github.com/xamarin/xamarin-macios/issues/15156) repository, this issue is from the Apple's MacCatalyst platform itself.
- I have tried a few approaches trying to find a workaround for it, however, since the platform itself is automatically selecting/deselecting all text from the editor, it won't be possible for us to handle that.
- Rolf from the xamarin-macios team mentioned this, which I tested and it works on those scenarios:

> Another point is that if you tab into the text view, or right click it, then the entire text is selected.

- I could not find any forum or insight of Apple plans to fix this issue of selecting/deselecting all in MacCatalyst.
- I tried also to trigger the right-click event when the Maui editor is focused without luck, in an effort to simulate it so the text gets selected, however, I could not find how to do it.

**Potential solutions/suggestions**

- Update the documentation with a special highlight note about MacCatalyst outlining that due to the platform limitations the select all text works when navigating with the tab into the text view or right click it. In the future, if a workaround is found we can certainly update it.

This is just my grain of salt.

Thank you!

**Comment by brminnick** [comment]
Love the idea of updating the docs! Could you [open a PR for it on our docs repo](https://github.com/MicrosoftDocs/CommunityToolkit)?

After the Docs PR is open, I'm happy to close this issue. We can always re-surface it if/when something changes on macOS.
