### ISSUE TITLE
[BUG] Crash when using Popup on 'OnAppearing' 

### ISSUE THREAD

**Issue by osnipezzini** [CommunityToolkit/Maui#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Popup called from OnAppearing on Windows, application crashes

### Expected Behavior

Expected to open Popup dialog with success

### Steps To Reproduce

Open and run solution from reproduction repository and wait for crash

### Link to public reproduction project repository

https://github.com/osnipezzini/MauiAppBugPopup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Windows 11 Build 22621.674
- .NET MAUI: 6.0.541
```

**Comment by pictos** [comment]
Hey @osnipezzini, thanks for reporting this issue. From my investigation this looks like a _timing_ error, so all the .NET MAUI objects are created before it shows on the screen. From my screenshot below you can see the `MainPage.Height` is `-1`, which means it doesn't get measured yet.

![image](https://user-images.githubusercontent.com/20712372/196009360-0e4b1faa-94ed-4b8e-aee4-b21e10b7bd37.png)

For now, the workaround will be adding a Delay before presenting the popup. Also, avoid using the `OnAppearing` method, the .net Maui team doesn't recommend it anymore, since it doesn't have a good, you can find more info about that [here](https://youtu.be/_EU5CovdSLY?t=1735).

```csharp
	protected override async void OnNavigatedTo(NavigatedToEventArgs args)
	{
		base.OnNavigatedTo(args);
		await Task.Delay(1_000);
		((MainViewModel)BindingContext).TestLoadCommand.Execute(null);
	}
```

Now talking about the solution, I don't have one yet... Need to see with the .net Maui team if there's a way to know if the app is started/presented and then we can hook up into that.

**Comment by osnipezzini** [comment]
Thanks @pictos this temp fix work for my situation too
