### ISSUE TITLE
[BUG] Custom control doesn't display in Popup

### ISSUE THREAD

**Issue by tsquillario** [CommunityToolkit/Maui#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a custom control to a Popup the control doesn't appear. No error.

### Expected Behavior

Control should display like it does on MainPage.xaml

### Steps To Reproduce

1. Clone and run repo
2. Click Open Popup button. The second Open Popup button is there to show the custom control works when on a ContentPage
3. Only 1 button is shown, this is not using the custom control. There should be 2 more buttons.

### Link to public reproduction project repository

https://github.com/tsquillario/MAUIToolkitPopupCustomControl

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1.0
- OS: Android 13
- .NET MAUI: 7.0
```

**Comment by pictos** [comment]
@tsquillario it appears here...
![Screenshot 2022-12-27 at 11 00 05](https://user-images.githubusercontent.com/20712372/209677287-8758b081-e3b6-4cd3-98dc-1d4b3153b13b.png)

Changing your popup's layout to be a `VerticalStack`, since you didn't configure the Grid Rows and Columns.
![Screenshot 2022-12-27 at 11 01 28](https://user-images.githubusercontent.com/20712372/209677464-420b3ee8-5b27-43bc-baa7-5e6cbf7ba0f1.png)

**Comment by VladislavAntonyuk** [comment]
As the reproduction, the author provided doesn't allow reproduce the issue I am going to add needs-reproduction label
