### ISSUE TITLE
[BUG] Popup on Android - "Could not locate MauiContext"

### ISSUE THREAD

**Issue by BioTurboNick** [CommunityToolkit/Maui#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Xamarin Exception Stack:
System.InvalidOperationException: Could not locate MauiContext.
  at CommunityToolkit.Maui.Views.PopupExtensions.CreatePopup(Page page, Popup popup)
  at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[ThreeButtonPopup](Page page, ThreeButtonPopup popup)
  at HemocytometerSidekick.Services.DialogManager.ShowPopupAsync(PopupViewModel popupData)
  at HemocytometerSidekick.Services.DialogManager.ShowStartResumeRequest(Action startCommand, Action resumeCommand)
  at HemocytometerSidekick.AppShell.BloodDifferential_Clicked(Object sender, EventArgs e)
  at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
  at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
  at Java.Lang.Thread.RunnableImplementor.Run()
  at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
```

### Expected Behavior

Popup shouldn't crash

### Steps To Reproduce

Unsure yet

### Link to public reproduction project repository

Not yet

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1.0
- OS: Android 10
- .NET MAUI: 7

So far, I've seen this reported 3x in the wild but seems to be from the same device. Redmi 9A, Android 10, Spanish language
```

### Anything else?

I'm going to fill this out more later.

Main question is what scenarios would lead to MauiContext not being found?

I saw a previous issue where the popup was being called before the app was fully loaded - a crash is fair there. But what about when it has loaded? If there are valid situations where MauiContext can't be found while the app is running, is there a more graceful way that could be handled internally?

**Comment by pictos** [comment]
@BioTurboNick are you trying to open the popup in the page that appears when the app is launched? On the OnAppearing method?

**Comment by BioTurboNick** [comment]
> @BioTurboNick are you trying to open the popup in the page that appears when the app is launched? On the OnAppearing method?

Nope, it's invoked when clicking an AppShell item.

Off-chance idea: someone clicking and accidentally activating an edge back-swipe (so app is going to sleep before the popup can display?)

**Comment by pictos** [comment]
> Off-chance idea: someone clicking and accidentally activating an edge back-swipe (so app is going to sleep before the popup can display?)

I don't think so... Anyway would be great if you could provide a sample project... I can't remember anything related to this. In general, we relly on MauiContext provided by Maui, so if it's `null` it's on Maui's end... Having a repro I can debug and see if we can workaround that (:

**Comment by BioTurboNick** [comment]
Sadly I can't locally reproduce it yet. I'll definitely update if I can learn more.

**Comment by pictos** [comment]
@BioTurboNick can you share a video reproducing the issue?

**Comment by BioTurboNick** [comment]
No, I've only seen it in AppCenter so far.

**Comment by BioTurboNick** [comment]
> This issue occurs when the Popup is launched from the `OnAppearing` method. Whereas invoking it from the `OnNavigatedTo` method works fine.

I'm not launching it from OnAppearing. It's launching from a user interaction with the AppShell.

**Comment by egvijayanand** [comment]
This issue occurs on Windows as well when invoked from the `OnAppearing` method, not specific to Android alone.

**Comment by egvijayanand** [comment]
> > This issue occurs when the Popup is launched from the `OnAppearing` method. Whereas invoking it from the `OnNavigatedTo` method works fine.
> 
> I'm not launching it from OnAppearing. It's launching from a user interaction with the AppShell.

I understand. But am facing the issue with the same error message when invoked from the `OnAppearing` method.

**Comment by BioTurboNick** [comment]
> > > This issue occurs when the Popup is launched from the `OnAppearing` method. Whereas invoking it from the `OnNavigatedTo` method works fine.
> > 
> > 
> > I'm not launching it from OnAppearing. It's launching from a user interaction with the AppShell.
> 
> I understand. But am facing the issue with the same error message when invoked from the `OnAppearing` method.

That's issue #693 btw

**Comment by BioTurboNick** [comment]
So I wonder if it's also a timing issue in my case, since it may be possible for the user to activate a navigation while the previous page hasn't completed loading.

**Comment by egvijayanand** [comment]
Thanks for pointing that out. Have searched with the error message before logging that as an issue and ended up here.

**Comment by BioTurboNick** [comment]
Maybe the error message could be more informative - Saying something about how the page may not be loaded at the time it's being called?

**Comment by BioTurboNick** [comment]
This shouldn't need reproduction and shouldn't go stale. 

I proposed a solution: amend the error message to point to the conditions in which it may occur (e.g. page hasn't completed loading)

**Comment by AdamBebko** [comment]
I was trying to use a popup to show a loading indicator. But I experienced this issue in both OnAppearing and OnNavigated. I fixed it by instead using this extension method, and calling it when calling `Shell.GoToAsync`.


```
 public static async Task GoToAsyncWithLoadingPopup(this Shell shell, string page)
    {
        SpinnerPopup currentPopup = new SpinnerPopup(); // This is my loading indicator popup
        Shell.Current.ShowPopup(currentPopup);
        await Shell.Current.GoToAsync(page);
        currentPopup.Close();
    }
```

then calling it like so:

`await Shell.Current.GoToAsyncWithLoadingPopup(nameof(MyPageThatShouldHaveLoadingIndicator));`

**Comment by pictos** [comment]
@AdamBebko, 
Can you share a link with a sample project?
Friendly reminder that we don't accept zip files, just repos on GitHub or GitLab, more info [here](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug)

**Comment by bijington** [comment]
@BioTurboNick we ask for a reproduction sample to help the person investigating the issue to firstly prove the issue and diagnose the cause. We can then also use it to prove that the issue has been resolved. 

I can see from the previous comments that you have been struggling to reproduce the issue. Perhaps we can continue the conversation to aid getting to a point of reproduction? If we can get to this point then I suspect we could add a lot more context into the exception message.

Can you confirm you have only seen this on Android?
I read that you have seen it on AppCenter? Are you running the application under test when it happens?

**Comment by BioTurboNick** [comment]
A reproduction isn't needed IMO because what's happening is just logic - Sometimes the page's Handler or MauiContext is null. That happens internally to MAUI and so the toolkit probably just has to deal with that.

Based on past reports, it sounds like the issue is likely related to the page not being fully created at the time the popup is being called, or potentially if the page is being disposed.

There are a finite number of ways to deal with that.
1. Get MauiContext through some alternate path
2. Detect that the Page hasn't finished being created, and provide a more specific error
3. Detect that the Page is being disposed, and provide a more specific error
4. Just provide an error that describes the conditions in which it may be thrown

(4) would be the easiest. I can't do much with "Could not locate MauiContext", but I can respond to "The Page you are trying to attach a Popup to may not yet be loaded or may be being disposed."

**Comment by BioTurboNick** [comment]
But for completness: I've only seen it on Android, but I haven't released an iOS MAUI version yet due to performance issues in MAUI.

I get many reports per day, from people running the app from the Play store.

I was able to instrument the exception in the most recent release and have found that in every instance it's happening in my case, the page's Handler is null.

**Comment by pictos** [comment]
@BioTurboNick 

> IMO because what's happening is just logic - Sometimes the page's Handler or MauiContext is null.


The `sometimes` makes it difficult to be `just logic`. To that be true, the issue should reproducible all the time for the same aspect. We can't change stuff having _guess_ as a basement. There's one place where the `MauiContext` is always `null`, like on the `OnAppearing` or `ctor` for the `MainPage`, and that's expected due to the lifecycle of .NET MAUI controls. You mentioned that wasn't your case, so we really need a repro to investigate that and do the correct fix.

When you or any other member of the community has a sample that we can use as a repro we will be more than happy to fix it or accept a PR fixing the issue.

Maybe you can record a video showing the exception happening, **MAYBE** we can infer what's going on from that.

**Comment by BioTurboNick** [comment]
Regardless, this issue should remain open.

**Comment by BioTurboNick** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1438610/213879268-943f21ba-27fb-4d1b-bc68-8204aa25892d.png">

**Comment by VladislavAntonyuk** [comment]
@BioTurboNick we understand that you have an issue. (As a workaround you can show a popup on the page loaded instead of appearing). But we kindly ask you to read the conversation again and provide a reproduction link or at least record a video. Without that info, we cannot move further and the issue will remain closed.

**Comment by BioTurboNick** [comment]
I'm not showing it in a page appearing handler. I'm trying to show it on the currently-loaded Shell page. If you're going to ask me to read the conversation again, can you do so as well, respectfully?

And, respectfully, I have also requested that at a minimum the error be more informative. If that is done then I'd be fine with the issue being closed. Why are you all resisting even that?

**Comment by BioTurboNick** [comment]
What bothers me most is that you all are demanding a reproduction (hours more of work) to take *any* action as simple as thinking through a better error message.

**Comment by BioTurboNick** [comment]
Thank you for the detailed reply.

> @BioTurboNick I don't have an issue with improving the message in the exception but that wouldn't solve the issue you are reporting. I would argue that without knowing what is causing your issue whatever we put into the message likely won't help.

No, but I'd rather leave the library better than it was before I filed the issue. And if in discussion you're all pretty confident that the only situation where it should be null is during loading, it's possible there's an unusual interaction in usage causing the problem, and not an issue with the toolkit.

> It does sound like there may be an issue with release builds if your users are reporting the issue. Just to confirm have you tried reproducing it in a release build?

Yes.

> On the topic of it taking hours to reproduce your issue, without the full context it can take us even longer to reproduce, if even possible. If you imagine us having to do that for all issues then we would just be spending all of our time reproducing the issues without being able to spend time fixing them. Given we dedicate our spare time to this maintaining this toolkit we need to be as efficient as we can with that time. That is why we ask for a reproduction. Sometimes it also helps us to realise that there was an issue with usage rather than the toolkit.

I'm not asking you all to reproduce it, it would just be nice to not have an attitude of "no reproduction, no help". I'm here as a collaborator in solving my problem.

> On to the issue at hand. I personally believe that we should look to implement the queuing based approach as seen in the MAUI codebase, allowing consumers to try and call `ShowPopup` from inside methods such as `OnAppearing`. I know this isn't your use case but it is the one concrete example we have that has caused issues and is reproducible. This change is something that I would like to seek the opinions of the rest of the team as it potentially adds extra maintenance onto us.

**Comment by VladislavAntonyuk** [comment]
Your suggestion for changing the error message may not be applicable to all scenarios, which is why we can't move with it further.

**Comment by bijington** [comment]
I am hopeful that #934 might help to solve the underlying issue that is happening here.

**Comment by BioTurboNick** [comment]
@bijington - that would be nice, thank you. I'll look forward to it being released and see if that fixes it.

**Comment by joshdadswellijyi** [comment]
@BioTurboNick Have you reached a solution to your problem as I beleive I am seeing the same problem with my app in the wild. As with you I am unable to reproduce it but it does seem to be distinct from the OnAppearing issue as mine is also triggered from the user clicking a button and not as part of any lifecycle events. Another issue is from logs I have received and screen captures I can see that the user can click the button over and over and it throws the same exception which implies that the issue is not that the page hasnt fully loaded yet as this happens over too long a period of time. 

Ideally looking for a fix for the problem but would also be nice to have a way of recovering from this problem that isnt close the app and start again.

`System.InvalidOperationException: Could not locate MauiContext.
   at CommunityToolkit.Maui.Views.PopupExtensions.CreatePopup(Page page, Popup popup)
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[ComboBoxPopup](Page page, ComboBoxPopup popup)
   at ITAL.SurveyTool.Services.NavigationService.ShowComboPopupAsync(ComboBoxPopupVM popupContext)
   at ITAL.SurveyTool.Commands.ComboBoxPopupCommand.ShowPopup(IComboBoxViewModel viewModel)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr ) --> System.InvalidOperationException: Could not locate MauiContext.
   at CommunityToolkit.Maui.Views.PopupExtensions.CreatePopup(Page page, Popup popup)
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[ComboBoxPopup](Page page, ComboBoxPopup popup)
   at ITAL.SurveyTool.Services.NavigationService.ShowComboPopupAsync(ComboBoxPopupVM popupContext)
   at ITAL.SurveyTool.Commands.ComboBoxPopupCommand.ShowPopup(IComboBoxViewModel viewModel)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )`

**Comment by BioTurboNick** [comment]
I haven't had an issue like this in quite some time. Though I'm still on CommunityToolkit 6.1.0.
